# Default values for croc-hunter.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
# Changing Service Type To LB for CLoud deployment on GKE or EKS or AKS
# Chnage it to NodePort if you are testing on Kind or Minikube etc.

serviceType: LoadBalancer
servicePort: 80
containerPort: 8080
component: "croc-hunter"
replicas: 2
image: "quay.io/lachie83/croc-hunter"
imageTag: "latest"
imagePullPolicy: "Always"
## If you have a private registry you specify a secret to use
#imagePullSecrets:
cpu: "10m"
memory: "128Mi"
## Ingress settings
ingress:
  enabled: false
  hostname: whatever.io . ## any domain you own
  annotations:
     kubernetes.io/ingress.class: nginx
     kubernetes.io/tls-acme: "true"
  tls: true
## PodDisruptionBudget
pdb:
  enabled: false
  minAvailable: 2
